services:
  mcp-weather-server:
    build: .
    container_name: mcp-weather-server
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=production
    env_file:
      - .env
    restart: unless-stopped
    volumes:
      # Volume pour la persistance des logs (optionnel)
      - ./logs:/app/logs
    networks:
      - mcp-network

  # Service optionnel pour un reverse proxy (nginx)
  nginx:
    image: nginx:alpine
    container_name: mcp-nginx
    ports:
      - "8080:80"
      - "8443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - mcp-weather-server
    networks:
      - mcp-network
    restart: unless-stopped

networks:
  mcp-network:
    driver: bridge

volumes:
  logs:
